site_name: Tabletopia - Русская база знаний
nav:
    - Playground:
        - playground/actions-with-game-objects.md
    - Workshop:
        - Создание игры:
            - workshop/games/how-to-create-game.md
            - workshop/games/how-to-prepare-graphics.md
            - workshop/games/filling-in-a-game-form.md
            - workshop/games/game-setups.md
            - workshop/games/play-zones.md
        - Создание объектов:
            - workshop/objects/game-objects-types.md
            - workshop/objects/how-to-fill-in-an-object-form.md
            - workshop/objects/objects-catalogue.md
            - workshop/objects/game-board.md
            - workshop/objects/card.md
            - workshop/objects/tile.md
            - workshop/objects/token.md
            - workshop/objects/counter.md
            - workshop/objects/die.md
            - workshop/objects/game-piece.md
            - workshop/objects/bag.md
            - workshop/objects/music-box.md
            - workshop/objects/picture-counter.md
            - workshop/objects/tables-surfaces-and-skyboxes.md
        - Улучшение игры:
            - workshop/enhance/visual-design-guide.md
            - workshop/enhance/randomizers.md
theme:
    name: "material"